site_name: Tutoriais do NPAD
theme:
   name: readthedocs
   highlightjs: true
   locale: pt_BR
   #logo: assets/logo_UFRN.png
#markdown_extensions:
#   - toc: 
#        baselevel: 1 
#        toc_depth: 2-4  
#   - pymdownx.highlight:
#      use_pygments: true
#   - pymdownx.superfences
nav:
   - Início: index.md
   - Iniciante:
      - beginner/superpc_introduction_part_1.md
      - beginner/superpc_introduction_part_2.md
      - 'Copiando Arquivos através de uma Interface gráfica Gnome Files (linux)': 'beginner/gnome_files.md'
      - 'Copiando Arquivos através de uma Interface gráfica WinSCP (Windows)': 'beginner/winscp_tutorial.md'
      - 'Transferir arquivos pelo terminal usando scp': 'beginner/scp_tutorial.md'
      - 'Transferir arquivos pelo terminal usando rsync (apenas linux)': 'beginner/rsync_tutorial.md'
      - 'PuTTy tutoriais': 'beginner/putty_tutorial.md'
      - 'MobaXterm Tutoriais': 'beginner/mobaxterm_tutorial.md'
   - Intermediário:
      - 'Introdução ao Supercomputador - Parte&nbsp;3': 'intermediate/superpc_introduction_part_3.md'
      - 'Comandos Slurm': 'intermediate/slurm_commands.md'
      - 'Instalação de Programas': 'intermediate/install_apps.md'
   - Avançado:
      - 'Tutorial OpenMP': 'advanced/openmp_tutorial.md'
      - 'Tutorial MPI': 'advanced/mpi_tutorial.md'
      - 'Executando Pytorch Rust na partição de gpu': 'advanced/tch-rs_tutorial.md'
      - 'Tutorial Jupyter': 'advanced/jupyter_tutorial.md' 
